package ohos_app_cangjie_entry.repository

public import ohos_app_cangjie_entry.repository.academic.*
public import ohos_app_cangjie_entry.repository.auth.*
public import ohos_app_cangjie_entry.repository.class_attendance.*
public import ohos_app_cangjie_entry.repository.classtable.*
public import ohos_app_cangjie_entry.repository.custom_class.*
public import ohos_app_cangjie_entry.repository.dorm_water.*
public import ohos_app_cangjie_entry.repository.empty_classroom.*
public import ohos_app_cangjie_entry.repository.energy.*
public import ohos_app_cangjie_entry.repository.experiment.*
public import ohos_app_cangjie_entry.repository.library.*
public import ohos_app_cangjie_entry.repository.pig.*
public import ohos_app_cangjie_entry.repository.school_card.*
public import ohos_app_cangjie_entry.repository.schoolnet.*
public import ohos_app_cangjie_entry.repository.sport.*
